# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-12 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans_app', '0003_auto_20180522_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans_app.Loans')),
            ],
        ),
    ]
