# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=4, max_digits=14)),
                ('original_balance', models.DecimalField(decimal_places=4, max_digits=14)),
                ('interest_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TestLoans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose', models.CharField(choices=[('1', 'One'), ('2', 'One'), ('3', 'One')], max_length=5)),
            ],
        ),
    ]
