# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testloans',
            name='test_decimal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='testloans',
            name='choose',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three')], max_length=5),
        ),
    ]
