# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0002_auto_20180522_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='testloans',
            name='test2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loans',
            name='current_balance',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='interest_rate',
            field=models.FloatField(verbose_name='Interest Rate'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='original_balance',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Original Balance'),
        ),
    ]
